version: '2'
services:
  bazarv3-app:
    image: bazarv3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bazarv3-postgresql:5432/bazarv3
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bazarv3-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bazarv3-elasticsearch:9200
    ports:
      - 8080:8080
  bazarv3-postgresql:
    extends:
      file: postgresql.yml
      service: bazarv3-postgresql
  bazarv3-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bazarv3-elasticsearch
